FROM eclipse-temurin:21-jre

COPY target/botanicare-0.0.1-SNAPSHOT.jar botanicare-0.0.1-SNAPSHOT.jar

ARG FIREBASE_SERVICE_ACCOUNT_ARG

ENV FIREBASE_SERVICE_ACCOUNT=$FIREBASE_SERVICE_ACCOUNT_ARG

EXPOSE 8443

ENTRYPOINT ["java","-jar","/botanicare-0.0.1-SNAPSHOT.jar"]