FROM eclipse-temurin:21-jre

COPY target/vocalmentor-backend-0.0.1-SNAPSHOT.jar vocalmentor-backend-0.0.1-SNAPSHOT.jar

EXPOSE 8443

ENTRYPOINT ["java","-jar","/vocalmentor-backend-0.0.1-SNAPSHOT.jar"]