spring:
  application:
    name: Botanicare
  datasource:
    url: jdbc:postgresql://localhost:5432/botanicaredatabase
    username: admin
    password: botanicare123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB